/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarCorreoRouteImport } from './routes/verificar-correo'
import { Route as RestablecerContrasenaRouteImport } from './routes/restablecer-contrasena'
import { Route as RecuperarContrasenaRouteImport } from './routes/recuperar-contrasena'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRequiredRouteImport } from './routes/admin-required'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccesoDenegadoRouteImport } from './routes/acceso-denegado'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OnboardingCustomizeRouteImport } from './routes/onboarding.customize'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppSincronizacionRouteImport } from './routes/app.sincronizacion'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppLogrosRouteImport } from './routes/app.logros'
import { Route as AppDescargasRouteImport } from './routes/app.descargas'
import { Route as AppClubesRouteImport } from './routes/app.clubes'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminTemasRouteImport } from './routes/admin.temas'
import { Route as AdminSendasRouteImport } from './routes/admin.sendas'
import { Route as AdminRevisionRouteImport } from './routes/admin.revision'
import { Route as AdminReportesRouteImport } from './routes/admin.reportes'
import { Route as AdminMediosRouteImport } from './routes/admin.medios'
import { Route as AdminClubesRouteImport } from './routes/admin.clubes'
import { Route as AdminAjustesRouteImport } from './routes/admin.ajustes'
import { Route as AdminActividadesRouteImport } from './routes/admin.actividades'
import { Route as AppTemasIndexRouteImport } from './routes/app.temas.index'
import { Route as AppTemasThemeIdRouteImport } from './routes/app.temas.$themeId'
import { Route as AppActividadesActivityIdRouteImport } from './routes/app.actividades.$activityId'
import { Route as AppR_relatarThemeIdRouteImport } from './routes/app.R_relatar.$themeId'
import { Route as AppR_recompensarThemeIdRouteImport } from './routes/app.R_recompensar.$themeId'
import { Route as AppE_experimentarThemeIdRouteImport } from './routes/app.E_experimentar.$themeId'
import { Route as AppE_ensenarThemeIdRouteImport } from './routes/app.E_ensenar.$themeId'
import { Route as AppC_conectarThemeIdRouteImport } from './routes/app.C_conectar.$themeId'
import { Route as AppC_comprobarThemeIdRouteImport } from './routes/app.C_comprobar.$themeId'
import { Route as AdminTemasNewRouteImport } from './routes/admin.temas.new'
import { Route as AdminTemasThemeIdPreviewRouteImport } from './routes/admin.temas.$themeId.preview'
import { Route as AdminTemasThemeIdEditRouteImport } from './routes/admin.temas.$themeId.edit'
import { Route as AdminTemasThemeIdDetalleRouteImport } from './routes/admin.temas.$themeId.detalle'
import { Route as AdminTemasThemeIdCrecerRouteImport } from './routes/admin.temas.$themeId.crecer'
import { Route as AdminTemasThemeIdActivitiesRouteImport } from './routes/admin.temas.$themeId.activities'

const VerificarCorreoRoute = VerificarCorreoRouteImport.update({
  id: '/verificar-correo',
  path: '/verificar-correo',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerContrasenaRoute = RestablecerContrasenaRouteImport.update({
  id: '/restablecer-contrasena',
  path: '/restablecer-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarContrasenaRoute = RecuperarContrasenaRouteImport.update({
  id: '/recuperar-contrasena',
  path: '/recuperar-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequiredRoute = AdminRequiredRouteImport.update({
  id: '/admin-required',
  path: '/admin-required',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoDenegadoRoute = AccesoDenegadoRouteImport.update({
  id: '/acceso-denegado',
  path: '/acceso-denegado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OnboardingCustomizeRoute = OnboardingCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSincronizacionRoute = AppSincronizacionRouteImport.update({
  id: '/sincronizacion',
  path: '/sincronizacion',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppLogrosRoute = AppLogrosRouteImport.update({
  id: '/logros',
  path: '/logros',
  getParentRoute: () => AppRoute,
} as any)
const AppDescargasRoute = AppDescargasRouteImport.update({
  id: '/descargas',
  path: '/descargas',
  getParentRoute: () => AppRoute,
} as any)
const AppClubesRoute = AppClubesRouteImport.update({
  id: '/clubes',
  path: '/clubes',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemasRoute = AdminTemasRouteImport.update({
  id: '/temas',
  path: '/temas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSendasRoute = AdminSendasRouteImport.update({
  id: '/sendas',
  path: '/sendas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevisionRoute = AdminRevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediosRoute = AdminMediosRouteImport.update({
  id: '/medios',
  path: '/medios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClubesRoute = AdminClubesRouteImport.update({
  id: '/clubes',
  path: '/clubes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAjustesRoute = AdminAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActividadesRoute = AdminActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => AdminRoute,
} as any)
const AppTemasIndexRoute = AppTemasIndexRouteImport.update({
  id: '/temas/',
  path: '/temas/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemasThemeIdRoute = AppTemasThemeIdRouteImport.update({
  id: '/temas/$themeId',
  path: '/temas/$themeId',
  getParentRoute: () => AppRoute,
} as any)
const AppActividadesActivityIdRoute =
  AppActividadesActivityIdRouteImport.update({
    id: '/actividades/$activityId',
    path: '/actividades/$activityId',
    getParentRoute: () => AppRoute,
  } as any)
const AppR_relatarThemeIdRoute = AppR_relatarThemeIdRouteImport.update({
  id: '/R_relatar/$themeId',
  path: '/R_relatar/$themeId',
  getParentRoute: () => AppRoute,
} as any)
const AppR_recompensarThemeIdRoute = AppR_recompensarThemeIdRouteImport.update({
  id: '/R_recompensar/$themeId',
  path: '/R_recompensar/$themeId',
  getParentRoute: () => AppRoute,
} as any)
const AppE_experimentarThemeIdRoute =
  AppE_experimentarThemeIdRouteImport.update({
    id: '/E_experimentar/$themeId',
    path: '/E_experimentar/$themeId',
    getParentRoute: () => AppRoute,
  } as any)
const AppE_ensenarThemeIdRoute = AppE_ensenarThemeIdRouteImport.update({
  id: '/E_ensenar/$themeId',
  path: '/E_ensenar/$themeId',
  getParentRoute: () => AppRoute,
} as any)
const AppC_conectarThemeIdRoute = AppC_conectarThemeIdRouteImport.update({
  id: '/C_conectar/$themeId',
  path: '/C_conectar/$themeId',
  getParentRoute: () => AppRoute,
} as any)
const AppC_comprobarThemeIdRoute = AppC_comprobarThemeIdRouteImport.update({
  id: '/C_comprobar/$themeId',
  path: '/C_comprobar/$themeId',
  getParentRoute: () => AppRoute,
} as any)
const AdminTemasNewRoute = AdminTemasNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTemasRoute,
} as any)
const AdminTemasThemeIdPreviewRoute =
  AdminTemasThemeIdPreviewRouteImport.update({
    id: '/$themeId/preview',
    path: '/$themeId/preview',
    getParentRoute: () => AdminTemasRoute,
  } as any)
const AdminTemasThemeIdEditRoute = AdminTemasThemeIdEditRouteImport.update({
  id: '/$themeId/edit',
  path: '/$themeId/edit',
  getParentRoute: () => AdminTemasRoute,
} as any)
const AdminTemasThemeIdDetalleRoute =
  AdminTemasThemeIdDetalleRouteImport.update({
    id: '/$themeId/detalle',
    path: '/$themeId/detalle',
    getParentRoute: () => AdminTemasRoute,
  } as any)
const AdminTemasThemeIdCrecerRoute = AdminTemasThemeIdCrecerRouteImport.update({
  id: '/$themeId/crecer',
  path: '/$themeId/crecer',
  getParentRoute: () => AdminTemasRoute,
} as any)
const AdminTemasThemeIdActivitiesRoute =
  AdminTemasThemeIdActivitiesRouteImport.update({
    id: '/$themeId/activities',
    path: '/$themeId/activities',
    getParentRoute: () => AdminTemasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso-denegado': typeof AccesoDenegadoRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-required': typeof AdminRequiredRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/verificar-correo': typeof VerificarCorreoRoute
  '/admin/actividades': typeof AdminActividadesRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/clubes': typeof AdminClubesRoute
  '/admin/medios': typeof AdminMediosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/revision': typeof AdminRevisionRoute
  '/admin/sendas': typeof AdminSendasRoute
  '/admin/temas': typeof AdminTemasRouteWithChildren
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/clubes': typeof AppClubesRoute
  '/app/descargas': typeof AppDescargasRoute
  '/app/logros': typeof AppLogrosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/sincronizacion': typeof AppSincronizacionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/customize': typeof OnboardingCustomizeRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/admin/temas/new': typeof AdminTemasNewRoute
  '/app/C_comprobar/$themeId': typeof AppC_comprobarThemeIdRoute
  '/app/C_conectar/$themeId': typeof AppC_conectarThemeIdRoute
  '/app/E_ensenar/$themeId': typeof AppE_ensenarThemeIdRoute
  '/app/E_experimentar/$themeId': typeof AppE_experimentarThemeIdRoute
  '/app/R_recompensar/$themeId': typeof AppR_recompensarThemeIdRoute
  '/app/R_relatar/$themeId': typeof AppR_relatarThemeIdRoute
  '/app/actividades/$activityId': typeof AppActividadesActivityIdRoute
  '/app/temas/$themeId': typeof AppTemasThemeIdRoute
  '/app/temas/': typeof AppTemasIndexRoute
  '/admin/temas/$themeId/activities': typeof AdminTemasThemeIdActivitiesRoute
  '/admin/temas/$themeId/crecer': typeof AdminTemasThemeIdCrecerRoute
  '/admin/temas/$themeId/detalle': typeof AdminTemasThemeIdDetalleRoute
  '/admin/temas/$themeId/edit': typeof AdminTemasThemeIdEditRoute
  '/admin/temas/$themeId/preview': typeof AdminTemasThemeIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso-denegado': typeof AccesoDenegadoRoute
  '/admin-required': typeof AdminRequiredRoute
  '/login': typeof LoginRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/verificar-correo': typeof VerificarCorreoRoute
  '/admin/actividades': typeof AdminActividadesRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/clubes': typeof AdminClubesRoute
  '/admin/medios': typeof AdminMediosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/revision': typeof AdminRevisionRoute
  '/admin/sendas': typeof AdminSendasRoute
  '/admin/temas': typeof AdminTemasRouteWithChildren
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/clubes': typeof AppClubesRoute
  '/app/descargas': typeof AppDescargasRoute
  '/app/logros': typeof AppLogrosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/sincronizacion': typeof AppSincronizacionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/customize': typeof OnboardingCustomizeRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/admin/temas/new': typeof AdminTemasNewRoute
  '/app/C_comprobar/$themeId': typeof AppC_comprobarThemeIdRoute
  '/app/C_conectar/$themeId': typeof AppC_conectarThemeIdRoute
  '/app/E_ensenar/$themeId': typeof AppE_ensenarThemeIdRoute
  '/app/E_experimentar/$themeId': typeof AppE_experimentarThemeIdRoute
  '/app/R_recompensar/$themeId': typeof AppR_recompensarThemeIdRoute
  '/app/R_relatar/$themeId': typeof AppR_relatarThemeIdRoute
  '/app/actividades/$activityId': typeof AppActividadesActivityIdRoute
  '/app/temas/$themeId': typeof AppTemasThemeIdRoute
  '/app/temas': typeof AppTemasIndexRoute
  '/admin/temas/$themeId/activities': typeof AdminTemasThemeIdActivitiesRoute
  '/admin/temas/$themeId/crecer': typeof AdminTemasThemeIdCrecerRoute
  '/admin/temas/$themeId/detalle': typeof AdminTemasThemeIdDetalleRoute
  '/admin/temas/$themeId/edit': typeof AdminTemasThemeIdEditRoute
  '/admin/temas/$themeId/preview': typeof AdminTemasThemeIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceso-denegado': typeof AccesoDenegadoRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-required': typeof AdminRequiredRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/verificar-correo': typeof VerificarCorreoRoute
  '/admin/actividades': typeof AdminActividadesRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/clubes': typeof AdminClubesRoute
  '/admin/medios': typeof AdminMediosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/revision': typeof AdminRevisionRoute
  '/admin/sendas': typeof AdminSendasRoute
  '/admin/temas': typeof AdminTemasRouteWithChildren
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/clubes': typeof AppClubesRoute
  '/app/descargas': typeof AppDescargasRoute
  '/app/logros': typeof AppLogrosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/sincronizacion': typeof AppSincronizacionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/customize': typeof OnboardingCustomizeRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/admin/temas/new': typeof AdminTemasNewRoute
  '/app/C_comprobar/$themeId': typeof AppC_comprobarThemeIdRoute
  '/app/C_conectar/$themeId': typeof AppC_conectarThemeIdRoute
  '/app/E_ensenar/$themeId': typeof AppE_ensenarThemeIdRoute
  '/app/E_experimentar/$themeId': typeof AppE_experimentarThemeIdRoute
  '/app/R_recompensar/$themeId': typeof AppR_recompensarThemeIdRoute
  '/app/R_relatar/$themeId': typeof AppR_relatarThemeIdRoute
  '/app/actividades/$activityId': typeof AppActividadesActivityIdRoute
  '/app/temas/$themeId': typeof AppTemasThemeIdRoute
  '/app/temas/': typeof AppTemasIndexRoute
  '/admin/temas/$themeId/activities': typeof AdminTemasThemeIdActivitiesRoute
  '/admin/temas/$themeId/crecer': typeof AdminTemasThemeIdCrecerRoute
  '/admin/temas/$themeId/detalle': typeof AdminTemasThemeIdDetalleRoute
  '/admin/temas/$themeId/edit': typeof AdminTemasThemeIdEditRoute
  '/admin/temas/$themeId/preview': typeof AdminTemasThemeIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso-denegado'
    | '/admin'
    | '/admin-required'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/recuperar-contrasena'
    | '/restablecer-contrasena'
    | '/verificar-correo'
    | '/admin/actividades'
    | '/admin/ajustes'
    | '/admin/clubes'
    | '/admin/medios'
    | '/admin/reportes'
    | '/admin/revision'
    | '/admin/sendas'
    | '/admin/temas'
    | '/admin/usuarios'
    | '/app/clubes'
    | '/app/descargas'
    | '/app/logros'
    | '/app/perfil'
    | '/app/sincronizacion'
    | '/auth/callback'
    | '/onboarding/customize'
    | '/admin/'
    | '/app/'
    | '/onboarding/'
    | '/admin/temas/new'
    | '/app/C_comprobar/$themeId'
    | '/app/C_conectar/$themeId'
    | '/app/E_ensenar/$themeId'
    | '/app/E_experimentar/$themeId'
    | '/app/R_recompensar/$themeId'
    | '/app/R_relatar/$themeId'
    | '/app/actividades/$activityId'
    | '/app/temas/$themeId'
    | '/app/temas/'
    | '/admin/temas/$themeId/activities'
    | '/admin/temas/$themeId/crecer'
    | '/admin/temas/$themeId/detalle'
    | '/admin/temas/$themeId/edit'
    | '/admin/temas/$themeId/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso-denegado'
    | '/admin-required'
    | '/login'
    | '/recuperar-contrasena'
    | '/restablecer-contrasena'
    | '/verificar-correo'
    | '/admin/actividades'
    | '/admin/ajustes'
    | '/admin/clubes'
    | '/admin/medios'
    | '/admin/reportes'
    | '/admin/revision'
    | '/admin/sendas'
    | '/admin/temas'
    | '/admin/usuarios'
    | '/app/clubes'
    | '/app/descargas'
    | '/app/logros'
    | '/app/perfil'
    | '/app/sincronizacion'
    | '/auth/callback'
    | '/onboarding/customize'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/admin/temas/new'
    | '/app/C_comprobar/$themeId'
    | '/app/C_conectar/$themeId'
    | '/app/E_ensenar/$themeId'
    | '/app/E_experimentar/$themeId'
    | '/app/R_recompensar/$themeId'
    | '/app/R_relatar/$themeId'
    | '/app/actividades/$activityId'
    | '/app/temas/$themeId'
    | '/app/temas'
    | '/admin/temas/$themeId/activities'
    | '/admin/temas/$themeId/crecer'
    | '/admin/temas/$themeId/detalle'
    | '/admin/temas/$themeId/edit'
    | '/admin/temas/$themeId/preview'
  id:
    | '__root__'
    | '/'
    | '/acceso-denegado'
    | '/admin'
    | '/admin-required'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/recuperar-contrasena'
    | '/restablecer-contrasena'
    | '/verificar-correo'
    | '/admin/actividades'
    | '/admin/ajustes'
    | '/admin/clubes'
    | '/admin/medios'
    | '/admin/reportes'
    | '/admin/revision'
    | '/admin/sendas'
    | '/admin/temas'
    | '/admin/usuarios'
    | '/app/clubes'
    | '/app/descargas'
    | '/app/logros'
    | '/app/perfil'
    | '/app/sincronizacion'
    | '/auth/callback'
    | '/onboarding/customize'
    | '/admin/'
    | '/app/'
    | '/onboarding/'
    | '/admin/temas/new'
    | '/app/C_comprobar/$themeId'
    | '/app/C_conectar/$themeId'
    | '/app/E_ensenar/$themeId'
    | '/app/E_experimentar/$themeId'
    | '/app/R_recompensar/$themeId'
    | '/app/R_relatar/$themeId'
    | '/app/actividades/$activityId'
    | '/app/temas/$themeId'
    | '/app/temas/'
    | '/admin/temas/$themeId/activities'
    | '/admin/temas/$themeId/crecer'
    | '/admin/temas/$themeId/detalle'
    | '/admin/temas/$themeId/edit'
    | '/admin/temas/$themeId/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoDenegadoRoute: typeof AccesoDenegadoRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminRequiredRoute: typeof AdminRequiredRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  RecuperarContrasenaRoute: typeof RecuperarContrasenaRoute
  RestablecerContrasenaRoute: typeof RestablecerContrasenaRoute
  VerificarCorreoRoute: typeof VerificarCorreoRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar-correo': {
      id: '/verificar-correo'
      path: '/verificar-correo'
      fullPath: '/verificar-correo'
      preLoaderRoute: typeof VerificarCorreoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer-contrasena': {
      id: '/restablecer-contrasena'
      path: '/restablecer-contrasena'
      fullPath: '/restablecer-contrasena'
      preLoaderRoute: typeof RestablecerContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-contrasena': {
      id: '/recuperar-contrasena'
      path: '/recuperar-contrasena'
      fullPath: '/recuperar-contrasena'
      preLoaderRoute: typeof RecuperarContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-required': {
      id: '/admin-required'
      path: '/admin-required'
      fullPath: '/admin-required'
      preLoaderRoute: typeof AdminRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso-denegado': {
      id: '/acceso-denegado'
      path: '/acceso-denegado'
      fullPath: '/acceso-denegado'
      preLoaderRoute: typeof AccesoDenegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/onboarding/customize': {
      id: '/onboarding/customize'
      path: '/customize'
      fullPath: '/onboarding/customize'
      preLoaderRoute: typeof OnboardingCustomizeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sincronizacion': {
      id: '/app/sincronizacion'
      path: '/sincronizacion'
      fullPath: '/app/sincronizacion'
      preLoaderRoute: typeof AppSincronizacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logros': {
      id: '/app/logros'
      path: '/logros'
      fullPath: '/app/logros'
      preLoaderRoute: typeof AppLogrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/descargas': {
      id: '/app/descargas'
      path: '/descargas'
      fullPath: '/app/descargas'
      preLoaderRoute: typeof AppDescargasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clubes': {
      id: '/app/clubes'
      path: '/clubes'
      fullPath: '/app/clubes'
      preLoaderRoute: typeof AppClubesRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/temas': {
      id: '/admin/temas'
      path: '/temas'
      fullPath: '/admin/temas'
      preLoaderRoute: typeof AdminTemasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sendas': {
      id: '/admin/sendas'
      path: '/sendas'
      fullPath: '/admin/sendas'
      preLoaderRoute: typeof AdminSendasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revision': {
      id: '/admin/revision'
      path: '/revision'
      fullPath: '/admin/revision'
      preLoaderRoute: typeof AdminRevisionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/medios': {
      id: '/admin/medios'
      path: '/medios'
      fullPath: '/admin/medios'
      preLoaderRoute: typeof AdminMediosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clubes': {
      id: '/admin/clubes'
      path: '/clubes'
      fullPath: '/admin/clubes'
      preLoaderRoute: typeof AdminClubesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ajustes': {
      id: '/admin/ajustes'
      path: '/ajustes'
      fullPath: '/admin/ajustes'
      preLoaderRoute: typeof AdminAjustesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/actividades': {
      id: '/admin/actividades'
      path: '/actividades'
      fullPath: '/admin/actividades'
      preLoaderRoute: typeof AdminActividadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/temas/': {
      id: '/app/temas/'
      path: '/temas'
      fullPath: '/app/temas/'
      preLoaderRoute: typeof AppTemasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/temas/$themeId': {
      id: '/app/temas/$themeId'
      path: '/temas/$themeId'
      fullPath: '/app/temas/$themeId'
      preLoaderRoute: typeof AppTemasThemeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/actividades/$activityId': {
      id: '/app/actividades/$activityId'
      path: '/actividades/$activityId'
      fullPath: '/app/actividades/$activityId'
      preLoaderRoute: typeof AppActividadesActivityIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/R_relatar/$themeId': {
      id: '/app/R_relatar/$themeId'
      path: '/R_relatar/$themeId'
      fullPath: '/app/R_relatar/$themeId'
      preLoaderRoute: typeof AppR_relatarThemeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/R_recompensar/$themeId': {
      id: '/app/R_recompensar/$themeId'
      path: '/R_recompensar/$themeId'
      fullPath: '/app/R_recompensar/$themeId'
      preLoaderRoute: typeof AppR_recompensarThemeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/E_experimentar/$themeId': {
      id: '/app/E_experimentar/$themeId'
      path: '/E_experimentar/$themeId'
      fullPath: '/app/E_experimentar/$themeId'
      preLoaderRoute: typeof AppE_experimentarThemeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/E_ensenar/$themeId': {
      id: '/app/E_ensenar/$themeId'
      path: '/E_ensenar/$themeId'
      fullPath: '/app/E_ensenar/$themeId'
      preLoaderRoute: typeof AppE_ensenarThemeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/C_conectar/$themeId': {
      id: '/app/C_conectar/$themeId'
      path: '/C_conectar/$themeId'
      fullPath: '/app/C_conectar/$themeId'
      preLoaderRoute: typeof AppC_conectarThemeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/C_comprobar/$themeId': {
      id: '/app/C_comprobar/$themeId'
      path: '/C_comprobar/$themeId'
      fullPath: '/app/C_comprobar/$themeId'
      preLoaderRoute: typeof AppC_comprobarThemeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/temas/new': {
      id: '/admin/temas/new'
      path: '/new'
      fullPath: '/admin/temas/new'
      preLoaderRoute: typeof AdminTemasNewRouteImport
      parentRoute: typeof AdminTemasRoute
    }
    '/admin/temas/$themeId/preview': {
      id: '/admin/temas/$themeId/preview'
      path: '/$themeId/preview'
      fullPath: '/admin/temas/$themeId/preview'
      preLoaderRoute: typeof AdminTemasThemeIdPreviewRouteImport
      parentRoute: typeof AdminTemasRoute
    }
    '/admin/temas/$themeId/edit': {
      id: '/admin/temas/$themeId/edit'
      path: '/$themeId/edit'
      fullPath: '/admin/temas/$themeId/edit'
      preLoaderRoute: typeof AdminTemasThemeIdEditRouteImport
      parentRoute: typeof AdminTemasRoute
    }
    '/admin/temas/$themeId/detalle': {
      id: '/admin/temas/$themeId/detalle'
      path: '/$themeId/detalle'
      fullPath: '/admin/temas/$themeId/detalle'
      preLoaderRoute: typeof AdminTemasThemeIdDetalleRouteImport
      parentRoute: typeof AdminTemasRoute
    }
    '/admin/temas/$themeId/crecer': {
      id: '/admin/temas/$themeId/crecer'
      path: '/$themeId/crecer'
      fullPath: '/admin/temas/$themeId/crecer'
      preLoaderRoute: typeof AdminTemasThemeIdCrecerRouteImport
      parentRoute: typeof AdminTemasRoute
    }
    '/admin/temas/$themeId/activities': {
      id: '/admin/temas/$themeId/activities'
      path: '/$themeId/activities'
      fullPath: '/admin/temas/$themeId/activities'
      preLoaderRoute: typeof AdminTemasThemeIdActivitiesRouteImport
      parentRoute: typeof AdminTemasRoute
    }
  }
}

interface AdminTemasRouteChildren {
  AdminTemasNewRoute: typeof AdminTemasNewRoute
  AdminTemasThemeIdActivitiesRoute: typeof AdminTemasThemeIdActivitiesRoute
  AdminTemasThemeIdCrecerRoute: typeof AdminTemasThemeIdCrecerRoute
  AdminTemasThemeIdDetalleRoute: typeof AdminTemasThemeIdDetalleRoute
  AdminTemasThemeIdEditRoute: typeof AdminTemasThemeIdEditRoute
  AdminTemasThemeIdPreviewRoute: typeof AdminTemasThemeIdPreviewRoute
}

const AdminTemasRouteChildren: AdminTemasRouteChildren = {
  AdminTemasNewRoute: AdminTemasNewRoute,
  AdminTemasThemeIdActivitiesRoute: AdminTemasThemeIdActivitiesRoute,
  AdminTemasThemeIdCrecerRoute: AdminTemasThemeIdCrecerRoute,
  AdminTemasThemeIdDetalleRoute: AdminTemasThemeIdDetalleRoute,
  AdminTemasThemeIdEditRoute: AdminTemasThemeIdEditRoute,
  AdminTemasThemeIdPreviewRoute: AdminTemasThemeIdPreviewRoute,
}

const AdminTemasRouteWithChildren = AdminTemasRoute._addFileChildren(
  AdminTemasRouteChildren,
)

interface AdminRouteChildren {
  AdminActividadesRoute: typeof AdminActividadesRoute
  AdminAjustesRoute: typeof AdminAjustesRoute
  AdminClubesRoute: typeof AdminClubesRoute
  AdminMediosRoute: typeof AdminMediosRoute
  AdminReportesRoute: typeof AdminReportesRoute
  AdminRevisionRoute: typeof AdminRevisionRoute
  AdminSendasRoute: typeof AdminSendasRoute
  AdminTemasRoute: typeof AdminTemasRouteWithChildren
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActividadesRoute: AdminActividadesRoute,
  AdminAjustesRoute: AdminAjustesRoute,
  AdminClubesRoute: AdminClubesRoute,
  AdminMediosRoute: AdminMediosRoute,
  AdminReportesRoute: AdminReportesRoute,
  AdminRevisionRoute: AdminRevisionRoute,
  AdminSendasRoute: AdminSendasRoute,
  AdminTemasRoute: AdminTemasRouteWithChildren,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppClubesRoute: typeof AppClubesRoute
  AppDescargasRoute: typeof AppDescargasRoute
  AppLogrosRoute: typeof AppLogrosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppSincronizacionRoute: typeof AppSincronizacionRoute
  AppIndexRoute: typeof AppIndexRoute
  AppC_comprobarThemeIdRoute: typeof AppC_comprobarThemeIdRoute
  AppC_conectarThemeIdRoute: typeof AppC_conectarThemeIdRoute
  AppE_ensenarThemeIdRoute: typeof AppE_ensenarThemeIdRoute
  AppE_experimentarThemeIdRoute: typeof AppE_experimentarThemeIdRoute
  AppR_recompensarThemeIdRoute: typeof AppR_recompensarThemeIdRoute
  AppR_relatarThemeIdRoute: typeof AppR_relatarThemeIdRoute
  AppActividadesActivityIdRoute: typeof AppActividadesActivityIdRoute
  AppTemasThemeIdRoute: typeof AppTemasThemeIdRoute
  AppTemasIndexRoute: typeof AppTemasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClubesRoute: AppClubesRoute,
  AppDescargasRoute: AppDescargasRoute,
  AppLogrosRoute: AppLogrosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppSincronizacionRoute: AppSincronizacionRoute,
  AppIndexRoute: AppIndexRoute,
  AppC_comprobarThemeIdRoute: AppC_comprobarThemeIdRoute,
  AppC_conectarThemeIdRoute: AppC_conectarThemeIdRoute,
  AppE_ensenarThemeIdRoute: AppE_ensenarThemeIdRoute,
  AppE_experimentarThemeIdRoute: AppE_experimentarThemeIdRoute,
  AppR_recompensarThemeIdRoute: AppR_recompensarThemeIdRoute,
  AppR_relatarThemeIdRoute: AppR_relatarThemeIdRoute,
  AppActividadesActivityIdRoute: AppActividadesActivityIdRoute,
  AppTemasThemeIdRoute: AppTemasThemeIdRoute,
  AppTemasIndexRoute: AppTemasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingCustomizeRoute: typeof OnboardingCustomizeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCustomizeRoute: OnboardingCustomizeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoDenegadoRoute: AccesoDenegadoRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminRequiredRoute: AdminRequiredRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  RecuperarContrasenaRoute: RecuperarContrasenaRoute,
  RestablecerContrasenaRoute: RestablecerContrasenaRoute,
  VerificarCorreoRoute: VerificarCorreoRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
