/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OnboardingCustomizeRouteImport } from './routes/onboarding.customize'
import { Route as AppSendasRouteImport } from './routes/app.sendas'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppLogrosRouteImport } from './routes/app.logros'
import { Route as AppDescargasRouteImport } from './routes/app.descargas'
import { Route as AppClubesRouteImport } from './routes/app.clubes'
import { Route as AdminTemasRouteImport } from './routes/admin.temas'
import { Route as AppTemasIndexRouteImport } from './routes/app.temas.index'
import { Route as AppTemasThemeIdRouteImport } from './routes/app.temas.$themeId'
import { Route as AppSendasSendaIdRouteImport } from './routes/app.sendas.$sendaId'
import { Route as AppActividadesActivityIdRouteImport } from './routes/app.actividades.$activityId'
import { Route as AppR_relatarThemeIdRouteImport } from './routes/app.R_relatar.$themeId'
import { Route as AppR_recompensarThemeIdRouteImport } from './routes/app.R_recompensar.$themeId'
import { Route as AppE_experimentarThemeIdRouteImport } from './routes/app.E_experimentar.$themeId'
import { Route as AppE_ensenarThemeIdRouteImport } from './routes/app.E_ensenar.$themeId'
import { Route as AppC_conectarThemeIdRouteImport } from './routes/app.C_conectar.$themeId'
import { Route as AppC_comprobarThemeIdRouteImport } from './routes/app.C_comprobar.$themeId'
import { Route as AdminTemasNewRouteImport } from './routes/admin.temas.new'
import { Route as AdminTemasThemeIdPreviewRouteImport } from './routes/admin.temas.$themeId.preview'
import { Route as AdminTemasThemeIdEditRouteImport } from './routes/admin.temas.$themeId.edit'
import { Route as AdminTemasThemeIdCrecerRouteImport } from './routes/admin.temas.$themeId.crecer'
import { Route as AdminTemasThemeIdActivitiesRouteImport } from './routes/admin.temas.$themeId.activities'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OnboardingCustomizeRoute = OnboardingCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppSendasRoute = AppSendasRouteImport.update({
  id: '/sendas',
  path: '/sendas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppLogrosRoute = AppLogrosRouteImport.update({
  id: '/logros',
  path: '/logros',
  getParentRoute: () => AppRoute,
} as any)
const AppDescargasRoute = AppDescargasRouteImport.update({
  id: '/descargas',
  path: '/descargas',
  getParentRoute: () => AppRoute,
} as any)
const AppClubesRoute = AppClubesRouteImport.update({
  id: '/clubes',
  path: '/clubes',
  getParentRoute: () => AppRoute,
} as any)
const AdminTemasRoute = AdminTemasRouteImport.update({
  id: '/temas',
  path: '/temas',
  getParentRoute: () => AdminRoute,
} as any)
const AppTemasIndexRoute = AppTemasIndexRouteImport.update({
  id: '/temas/',
  path: '/temas/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemasThemeIdRoute = AppTemasThemeIdRouteImport.update({
  id: '/temas/$themeId',
  path: '/temas/$themeId',
  getParentRoute: () => AppRoute,
} as any)
const AppSendasSendaIdRoute = AppSendasSendaIdRouteImport.update({
  id: '/$sendaId',
  path: '/$sendaId',
  getParentRoute: () => AppSendasRoute,
} as any)
const AppActividadesActivityIdRoute =
  AppActividadesActivityIdRouteImport.update({
    id: '/actividades/$activityId',
    path: '/actividades/$activityId',
    getParentRoute: () => AppRoute,
  } as any)
const AppR_relatarThemeIdRoute = AppR_relatarThemeIdRouteImport.update({
  id: '/R_relatar/$themeId',
  path: '/R_relatar/$themeId',
  getParentRoute: () => AppRoute,
} as any)
const AppR_recompensarThemeIdRoute = AppR_recompensarThemeIdRouteImport.update({
  id: '/R_recompensar/$themeId',
  path: '/R_recompensar/$themeId',
  getParentRoute: () => AppRoute,
} as any)
const AppE_experimentarThemeIdRoute =
  AppE_experimentarThemeIdRouteImport.update({
    id: '/E_experimentar/$themeId',
    path: '/E_experimentar/$themeId',
    getParentRoute: () => AppRoute,
  } as any)
const AppE_ensenarThemeIdRoute = AppE_ensenarThemeIdRouteImport.update({
  id: '/E_ensenar/$themeId',
  path: '/E_ensenar/$themeId',
  getParentRoute: () => AppRoute,
} as any)
const AppC_conectarThemeIdRoute = AppC_conectarThemeIdRouteImport.update({
  id: '/C_conectar/$themeId',
  path: '/C_conectar/$themeId',
  getParentRoute: () => AppRoute,
} as any)
const AppC_comprobarThemeIdRoute = AppC_comprobarThemeIdRouteImport.update({
  id: '/C_comprobar/$themeId',
  path: '/C_comprobar/$themeId',
  getParentRoute: () => AppRoute,
} as any)
const AdminTemasNewRoute = AdminTemasNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTemasRoute,
} as any)
const AdminTemasThemeIdPreviewRoute =
  AdminTemasThemeIdPreviewRouteImport.update({
    id: '/$themeId/preview',
    path: '/$themeId/preview',
    getParentRoute: () => AdminTemasRoute,
  } as any)
const AdminTemasThemeIdEditRoute = AdminTemasThemeIdEditRouteImport.update({
  id: '/$themeId/edit',
  path: '/$themeId/edit',
  getParentRoute: () => AdminTemasRoute,
} as any)
const AdminTemasThemeIdCrecerRoute = AdminTemasThemeIdCrecerRouteImport.update({
  id: '/$themeId/crecer',
  path: '/$themeId/crecer',
  getParentRoute: () => AdminTemasRoute,
} as any)
const AdminTemasThemeIdActivitiesRoute =
  AdminTemasThemeIdActivitiesRouteImport.update({
    id: '/$themeId/activities',
    path: '/$themeId/activities',
    getParentRoute: () => AdminTemasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/admin/temas': typeof AdminTemasRouteWithChildren
  '/app/clubes': typeof AppClubesRoute
  '/app/descargas': typeof AppDescargasRoute
  '/app/logros': typeof AppLogrosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/sendas': typeof AppSendasRouteWithChildren
  '/onboarding/customize': typeof OnboardingCustomizeRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/admin/temas/new': typeof AdminTemasNewRoute
  '/app/C_comprobar/$themeId': typeof AppC_comprobarThemeIdRoute
  '/app/C_conectar/$themeId': typeof AppC_conectarThemeIdRoute
  '/app/E_ensenar/$themeId': typeof AppE_ensenarThemeIdRoute
  '/app/E_experimentar/$themeId': typeof AppE_experimentarThemeIdRoute
  '/app/R_recompensar/$themeId': typeof AppR_recompensarThemeIdRoute
  '/app/R_relatar/$themeId': typeof AppR_relatarThemeIdRoute
  '/app/actividades/$activityId': typeof AppActividadesActivityIdRoute
  '/app/sendas/$sendaId': typeof AppSendasSendaIdRoute
  '/app/temas/$themeId': typeof AppTemasThemeIdRoute
  '/app/temas/': typeof AppTemasIndexRoute
  '/admin/temas/$themeId/activities': typeof AdminTemasThemeIdActivitiesRoute
  '/admin/temas/$themeId/crecer': typeof AdminTemasThemeIdCrecerRoute
  '/admin/temas/$themeId/edit': typeof AdminTemasThemeIdEditRoute
  '/admin/temas/$themeId/preview': typeof AdminTemasThemeIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/temas': typeof AdminTemasRouteWithChildren
  '/app/clubes': typeof AppClubesRoute
  '/app/descargas': typeof AppDescargasRoute
  '/app/logros': typeof AppLogrosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/sendas': typeof AppSendasRouteWithChildren
  '/onboarding/customize': typeof OnboardingCustomizeRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/admin/temas/new': typeof AdminTemasNewRoute
  '/app/C_comprobar/$themeId': typeof AppC_comprobarThemeIdRoute
  '/app/C_conectar/$themeId': typeof AppC_conectarThemeIdRoute
  '/app/E_ensenar/$themeId': typeof AppE_ensenarThemeIdRoute
  '/app/E_experimentar/$themeId': typeof AppE_experimentarThemeIdRoute
  '/app/R_recompensar/$themeId': typeof AppR_recompensarThemeIdRoute
  '/app/R_relatar/$themeId': typeof AppR_relatarThemeIdRoute
  '/app/actividades/$activityId': typeof AppActividadesActivityIdRoute
  '/app/sendas/$sendaId': typeof AppSendasSendaIdRoute
  '/app/temas/$themeId': typeof AppTemasThemeIdRoute
  '/app/temas': typeof AppTemasIndexRoute
  '/admin/temas/$themeId/activities': typeof AdminTemasThemeIdActivitiesRoute
  '/admin/temas/$themeId/crecer': typeof AdminTemasThemeIdCrecerRoute
  '/admin/temas/$themeId/edit': typeof AdminTemasThemeIdEditRoute
  '/admin/temas/$themeId/preview': typeof AdminTemasThemeIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/admin/temas': typeof AdminTemasRouteWithChildren
  '/app/clubes': typeof AppClubesRoute
  '/app/descargas': typeof AppDescargasRoute
  '/app/logros': typeof AppLogrosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/sendas': typeof AppSendasRouteWithChildren
  '/onboarding/customize': typeof OnboardingCustomizeRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/admin/temas/new': typeof AdminTemasNewRoute
  '/app/C_comprobar/$themeId': typeof AppC_comprobarThemeIdRoute
  '/app/C_conectar/$themeId': typeof AppC_conectarThemeIdRoute
  '/app/E_ensenar/$themeId': typeof AppE_ensenarThemeIdRoute
  '/app/E_experimentar/$themeId': typeof AppE_experimentarThemeIdRoute
  '/app/R_recompensar/$themeId': typeof AppR_recompensarThemeIdRoute
  '/app/R_relatar/$themeId': typeof AppR_relatarThemeIdRoute
  '/app/actividades/$activityId': typeof AppActividadesActivityIdRoute
  '/app/sendas/$sendaId': typeof AppSendasSendaIdRoute
  '/app/temas/$themeId': typeof AppTemasThemeIdRoute
  '/app/temas/': typeof AppTemasIndexRoute
  '/admin/temas/$themeId/activities': typeof AdminTemasThemeIdActivitiesRoute
  '/admin/temas/$themeId/crecer': typeof AdminTemasThemeIdCrecerRoute
  '/admin/temas/$themeId/edit': typeof AdminTemasThemeIdEditRoute
  '/admin/temas/$themeId/preview': typeof AdminTemasThemeIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/admin/temas'
    | '/app/clubes'
    | '/app/descargas'
    | '/app/logros'
    | '/app/perfil'
    | '/app/sendas'
    | '/onboarding/customize'
    | '/admin/'
    | '/app/'
    | '/onboarding/'
    | '/admin/temas/new'
    | '/app/C_comprobar/$themeId'
    | '/app/C_conectar/$themeId'
    | '/app/E_ensenar/$themeId'
    | '/app/E_experimentar/$themeId'
    | '/app/R_recompensar/$themeId'
    | '/app/R_relatar/$themeId'
    | '/app/actividades/$activityId'
    | '/app/sendas/$sendaId'
    | '/app/temas/$themeId'
    | '/app/temas/'
    | '/admin/temas/$themeId/activities'
    | '/admin/temas/$themeId/crecer'
    | '/admin/temas/$themeId/edit'
    | '/admin/temas/$themeId/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/temas'
    | '/app/clubes'
    | '/app/descargas'
    | '/app/logros'
    | '/app/perfil'
    | '/app/sendas'
    | '/onboarding/customize'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/admin/temas/new'
    | '/app/C_comprobar/$themeId'
    | '/app/C_conectar/$themeId'
    | '/app/E_ensenar/$themeId'
    | '/app/E_experimentar/$themeId'
    | '/app/R_recompensar/$themeId'
    | '/app/R_relatar/$themeId'
    | '/app/actividades/$activityId'
    | '/app/sendas/$sendaId'
    | '/app/temas/$themeId'
    | '/app/temas'
    | '/admin/temas/$themeId/activities'
    | '/admin/temas/$themeId/crecer'
    | '/admin/temas/$themeId/edit'
    | '/admin/temas/$themeId/preview'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/admin/temas'
    | '/app/clubes'
    | '/app/descargas'
    | '/app/logros'
    | '/app/perfil'
    | '/app/sendas'
    | '/onboarding/customize'
    | '/admin/'
    | '/app/'
    | '/onboarding/'
    | '/admin/temas/new'
    | '/app/C_comprobar/$themeId'
    | '/app/C_conectar/$themeId'
    | '/app/E_ensenar/$themeId'
    | '/app/E_experimentar/$themeId'
    | '/app/R_recompensar/$themeId'
    | '/app/R_relatar/$themeId'
    | '/app/actividades/$activityId'
    | '/app/sendas/$sendaId'
    | '/app/temas/$themeId'
    | '/app/temas/'
    | '/admin/temas/$themeId/activities'
    | '/admin/temas/$themeId/crecer'
    | '/admin/temas/$themeId/edit'
    | '/admin/temas/$themeId/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/onboarding/customize': {
      id: '/onboarding/customize'
      path: '/customize'
      fullPath: '/onboarding/customize'
      preLoaderRoute: typeof OnboardingCustomizeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/app/sendas': {
      id: '/app/sendas'
      path: '/sendas'
      fullPath: '/app/sendas'
      preLoaderRoute: typeof AppSendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logros': {
      id: '/app/logros'
      path: '/logros'
      fullPath: '/app/logros'
      preLoaderRoute: typeof AppLogrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/descargas': {
      id: '/app/descargas'
      path: '/descargas'
      fullPath: '/app/descargas'
      preLoaderRoute: typeof AppDescargasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clubes': {
      id: '/app/clubes'
      path: '/clubes'
      fullPath: '/app/clubes'
      preLoaderRoute: typeof AppClubesRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/temas': {
      id: '/admin/temas'
      path: '/temas'
      fullPath: '/admin/temas'
      preLoaderRoute: typeof AdminTemasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/temas/': {
      id: '/app/temas/'
      path: '/temas'
      fullPath: '/app/temas/'
      preLoaderRoute: typeof AppTemasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/temas/$themeId': {
      id: '/app/temas/$themeId'
      path: '/temas/$themeId'
      fullPath: '/app/temas/$themeId'
      preLoaderRoute: typeof AppTemasThemeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sendas/$sendaId': {
      id: '/app/sendas/$sendaId'
      path: '/$sendaId'
      fullPath: '/app/sendas/$sendaId'
      preLoaderRoute: typeof AppSendasSendaIdRouteImport
      parentRoute: typeof AppSendasRoute
    }
    '/app/actividades/$activityId': {
      id: '/app/actividades/$activityId'
      path: '/actividades/$activityId'
      fullPath: '/app/actividades/$activityId'
      preLoaderRoute: typeof AppActividadesActivityIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/R_relatar/$themeId': {
      id: '/app/R_relatar/$themeId'
      path: '/R_relatar/$themeId'
      fullPath: '/app/R_relatar/$themeId'
      preLoaderRoute: typeof AppR_relatarThemeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/R_recompensar/$themeId': {
      id: '/app/R_recompensar/$themeId'
      path: '/R_recompensar/$themeId'
      fullPath: '/app/R_recompensar/$themeId'
      preLoaderRoute: typeof AppR_recompensarThemeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/E_experimentar/$themeId': {
      id: '/app/E_experimentar/$themeId'
      path: '/E_experimentar/$themeId'
      fullPath: '/app/E_experimentar/$themeId'
      preLoaderRoute: typeof AppE_experimentarThemeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/E_ensenar/$themeId': {
      id: '/app/E_ensenar/$themeId'
      path: '/E_ensenar/$themeId'
      fullPath: '/app/E_ensenar/$themeId'
      preLoaderRoute: typeof AppE_ensenarThemeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/C_conectar/$themeId': {
      id: '/app/C_conectar/$themeId'
      path: '/C_conectar/$themeId'
      fullPath: '/app/C_conectar/$themeId'
      preLoaderRoute: typeof AppC_conectarThemeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/C_comprobar/$themeId': {
      id: '/app/C_comprobar/$themeId'
      path: '/C_comprobar/$themeId'
      fullPath: '/app/C_comprobar/$themeId'
      preLoaderRoute: typeof AppC_comprobarThemeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/temas/new': {
      id: '/admin/temas/new'
      path: '/new'
      fullPath: '/admin/temas/new'
      preLoaderRoute: typeof AdminTemasNewRouteImport
      parentRoute: typeof AdminTemasRoute
    }
    '/admin/temas/$themeId/preview': {
      id: '/admin/temas/$themeId/preview'
      path: '/$themeId/preview'
      fullPath: '/admin/temas/$themeId/preview'
      preLoaderRoute: typeof AdminTemasThemeIdPreviewRouteImport
      parentRoute: typeof AdminTemasRoute
    }
    '/admin/temas/$themeId/edit': {
      id: '/admin/temas/$themeId/edit'
      path: '/$themeId/edit'
      fullPath: '/admin/temas/$themeId/edit'
      preLoaderRoute: typeof AdminTemasThemeIdEditRouteImport
      parentRoute: typeof AdminTemasRoute
    }
    '/admin/temas/$themeId/crecer': {
      id: '/admin/temas/$themeId/crecer'
      path: '/$themeId/crecer'
      fullPath: '/admin/temas/$themeId/crecer'
      preLoaderRoute: typeof AdminTemasThemeIdCrecerRouteImport
      parentRoute: typeof AdminTemasRoute
    }
    '/admin/temas/$themeId/activities': {
      id: '/admin/temas/$themeId/activities'
      path: '/$themeId/activities'
      fullPath: '/admin/temas/$themeId/activities'
      preLoaderRoute: typeof AdminTemasThemeIdActivitiesRouteImport
      parentRoute: typeof AdminTemasRoute
    }
  }
}

interface AdminTemasRouteChildren {
  AdminTemasNewRoute: typeof AdminTemasNewRoute
  AdminTemasThemeIdActivitiesRoute: typeof AdminTemasThemeIdActivitiesRoute
  AdminTemasThemeIdCrecerRoute: typeof AdminTemasThemeIdCrecerRoute
  AdminTemasThemeIdEditRoute: typeof AdminTemasThemeIdEditRoute
  AdminTemasThemeIdPreviewRoute: typeof AdminTemasThemeIdPreviewRoute
}

const AdminTemasRouteChildren: AdminTemasRouteChildren = {
  AdminTemasNewRoute: AdminTemasNewRoute,
  AdminTemasThemeIdActivitiesRoute: AdminTemasThemeIdActivitiesRoute,
  AdminTemasThemeIdCrecerRoute: AdminTemasThemeIdCrecerRoute,
  AdminTemasThemeIdEditRoute: AdminTemasThemeIdEditRoute,
  AdminTemasThemeIdPreviewRoute: AdminTemasThemeIdPreviewRoute,
}

const AdminTemasRouteWithChildren = AdminTemasRoute._addFileChildren(
  AdminTemasRouteChildren,
)

interface AdminRouteChildren {
  AdminTemasRoute: typeof AdminTemasRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTemasRoute: AdminTemasRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppSendasRouteChildren {
  AppSendasSendaIdRoute: typeof AppSendasSendaIdRoute
}

const AppSendasRouteChildren: AppSendasRouteChildren = {
  AppSendasSendaIdRoute: AppSendasSendaIdRoute,
}

const AppSendasRouteWithChildren = AppSendasRoute._addFileChildren(
  AppSendasRouteChildren,
)

interface AppRouteChildren {
  AppClubesRoute: typeof AppClubesRoute
  AppDescargasRoute: typeof AppDescargasRoute
  AppLogrosRoute: typeof AppLogrosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppSendasRoute: typeof AppSendasRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppC_comprobarThemeIdRoute: typeof AppC_comprobarThemeIdRoute
  AppC_conectarThemeIdRoute: typeof AppC_conectarThemeIdRoute
  AppE_ensenarThemeIdRoute: typeof AppE_ensenarThemeIdRoute
  AppE_experimentarThemeIdRoute: typeof AppE_experimentarThemeIdRoute
  AppR_recompensarThemeIdRoute: typeof AppR_recompensarThemeIdRoute
  AppR_relatarThemeIdRoute: typeof AppR_relatarThemeIdRoute
  AppActividadesActivityIdRoute: typeof AppActividadesActivityIdRoute
  AppTemasThemeIdRoute: typeof AppTemasThemeIdRoute
  AppTemasIndexRoute: typeof AppTemasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClubesRoute: AppClubesRoute,
  AppDescargasRoute: AppDescargasRoute,
  AppLogrosRoute: AppLogrosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppSendasRoute: AppSendasRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppC_comprobarThemeIdRoute: AppC_comprobarThemeIdRoute,
  AppC_conectarThemeIdRoute: AppC_conectarThemeIdRoute,
  AppE_ensenarThemeIdRoute: AppE_ensenarThemeIdRoute,
  AppE_experimentarThemeIdRoute: AppE_experimentarThemeIdRoute,
  AppR_recompensarThemeIdRoute: AppR_recompensarThemeIdRoute,
  AppR_relatarThemeIdRoute: AppR_relatarThemeIdRoute,
  AppActividadesActivityIdRoute: AppActividadesActivityIdRoute,
  AppTemasThemeIdRoute: AppTemasThemeIdRoute,
  AppTemasIndexRoute: AppTemasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingCustomizeRoute: typeof OnboardingCustomizeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCustomizeRoute: OnboardingCustomizeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
