import type { ActivityTableRow } from "../componentes/admin-activities-table";

export const mockupActivities: ActivityTableRow[] = [
  {
    id: "mock-1",
    titulo: "¿Quién dijo esto?",
    consigna: "Selecciona la respuesta correcta",
    tipoIcon: "fa-circle-question",
    tipoIconColor: "text-purple-600",
    tipoBadgeBg: "bg-purple-100",
    tipoNombre: "La creación de Dios",
    sendaNombre: "Dios y su amor",
    sendaIconColor: "text-[#3d8bd4]",
    franjaEdad: "Pequeños (6-8)",
    xpText: "+20 XP",
    estado: "publicada",
    fechaCreacion: "15 may. 2024"
  },
  {
    id: "mock-2",
    titulo: "Cartas: Frutos del Espíritu",
    consigna: "Conoce y memoriza",
    tipoIcon: "fa-book-open",
    tipoIconColor: "text-amber-500",
    tipoBadgeBg: "bg-amber-100",
    tipoNombre: "El perdón",
    sendaNombre: "Relaciones sanas",
    sendaIconColor: "text-[#17a398]",
    franjaEdad: "Medianos (9-11)",
    xpText: "+15 XP",
    estado: "publicada",
    fechaCreacion: "14 may. 2024"
  },
  {
    id: "mock-3",
    titulo: "Completa el versículo",
    consigna: "Filipenses 4:13",
    tipoIcon: "fa-pen-clip",
    tipoIconColor: "text-blue-500",
    tipoBadgeBg: "bg-blue-100",
    tipoNombre: "El Buen Samaritano",
    sendaNombre: "Amor al prójimo",
    sendaIconColor: "text-[#17a398]",
    franjaEdad: "Grandes (12-14)",
    xpText: "+25 XP",
    estado: "revision",
    fechaCreacion: "13 may. 2024"
  },
  {
    id: "mock-4",
    titulo: "¿Verdadero o falso?",
    consigna: "Pon a prueba tu conocimiento",
    tipoIcon: "fa-circle-check",
    tipoIconColor: "text-emerald-500",
    tipoBadgeBg: "bg-emerald-100",
    tipoNombre: "Daniel en el foso de los leones",
    sendaNombre: "Fe y valentía",
    sendaIconColor: "text-[#3d8bd4]",
    franjaEdad: "Medianos (9-11)",
    xpText: "+15 XP",
    estado: "publicada",
    fechaCreacion: "12 may. 2024"
  },
  {
    id: "mock-5",
    titulo: "Sopa de letras",
    consigna: "Encuentra las palabras",
    tipoIcon: "fa-border-all",
    tipoIconColor: "text-violet-600",
    tipoBadgeBg: "bg-violet-100",
    tipoNombre: "La oración",
    sendaNombre: "Vida con Jesús",
    sendaIconColor: "text-[#e9a23b]",
    franjaEdad: "Grandes (12-14)",
    xpText: "+20 XP",
    estado: "publicada",
    fechaCreacion: "11 may. 2024"
  },
  {
    id: "mock-6",
    titulo: "Ordena el versículo",
    consigna: "Pon en el orden correcto",
    tipoIcon: "fa-puzzle-piece",
    tipoIconColor: "text-orange-500",
    tipoBadgeBg: "bg-orange-100",
    tipoNombre: "El perdón",
    sendaNombre: "Relaciones sanas",
    sendaIconColor: "text-[#17a398]",
    franjaEdad: "Pequeños (6-8)",
    xpText: "+20 XP",
    estado: "borrador",
    fechaCreacion: "10 may. 2024"
  },
  {
    id: "mock-7",
    titulo: "Memoria: Pasajes clave",
    consigna: "Encuentra los pares",
    tipoIcon: "fa-image",
    tipoIconColor: "text-sky-500",
    tipoBadgeBg: "bg-sky-100",
    tipoNombre: "Dios cuida de mí",
    sendaNombre: "Confío en Dios",
    sendaIconColor: "text-[#3d8bd4]",
    franjaEdad: "Pequeños (6-8)",
    xpText: "+15 XP",
    estado: "publicada",
    fechaCreacion: "9 may. 2024"
  },
  {
    id: "mock-8",
    titulo: "Desafío express",
    consigna: "Responde rápido",
    tipoIcon: "fa-star",
    tipoIconColor: "text-pink-500",
    tipoBadgeBg: "bg-pink-100",
    tipoNombre: "La creación de Dios",
    sendaNombre: "Dios y su amor",
    sendaIconColor: "text-[#3d8bd4]",
    franjaEdad: "Medianos (9-11)",
    xpText: "+10 XP",
    estado: "revision",
    fechaCreacion: "8 may. 2024"
  }
];
