import type { ActivityTableRow } from "../componentes/admin-activities-table";
import { getSendaColorClasses } from "../componentes/actividades.helpers";

export const mockupActivities: ActivityTableRow[] = [
  {
    id: "mock-1",
    titulo: "¿Quién dijo esto?",
    consigna: "Selecciona la respuesta correcta",
    tipoIcon: "fa-circle-question",
    tipoIconColor: "text-purple-600",
    tipoBadgeBg: "bg-purple-100",
    tipoNombre: "Quiz",
    tipoCodigo: "quiz",
    temaId: "tema-1",
    temaNombre: "La creación de Dios",
    temaSlug: "la-creacion",
    temaEstado: "publicado",
    pasoId: null,
    franjaEdad: "Pequeños (6-8)",
    xpText: "+20 XP",
    xp: 20,
    estado: "publicada",
    fechaCreacion: "15 may. 2024",
    dificultad: "facil",
    consignaRaw: "Selecciona la respuesta correcta",
    opciones: [],
    sendaColor: getSendaColorClasses("Padre"),
    grupoEdadId: "grupo-1",
  },
  {
    id: "mock-2",
    titulo: "Cartas: Frutos del Espíritu",
    consigna: "Conoce y memoriza",
    tipoIcon: "fa-book-open",
    tipoIconColor: "text-amber-500",
    tipoBadgeBg: "bg-amber-100",
    tipoNombre: "Flashcard",
    tipoCodigo: "flashcard",
    temaId: "tema-2",
    temaNombre: "El perdón",
    temaSlug: "el-perdon",
    temaEstado: "publicado",
    pasoId: null,
    franjaEdad: "Medianos (9-11)",
    xpText: "+15 XP",
    xp: 15,
    estado: "publicada",
    fechaCreacion: "14 may. 2024",
    dificultad: "facil",
    consignaRaw: "Conoce y memoriza",
    opciones: [],
    sendaColor: getSendaColorClasses("Espíritu"),
    grupoEdadId: "grupo-2",
  },
  {
    id: "mock-3",
    titulo: "Completa el versículo",
    consigna: "Filipenses 4:13",
    tipoIcon: "fa-pen-clip",
    tipoIconColor: "text-blue-500",
    tipoBadgeBg: "bg-blue-100",
    tipoNombre: "Completar versículo",
    tipoCodigo: "completar_verso",
    temaId: "tema-3",
    temaNombre: "El Buen Samaritano",
    temaSlug: "buen-samaritano",
    temaEstado: "revision",
    pasoId: null,
    franjaEdad: "Grandes (12-14)",
    xpText: "+25 XP",
    xp: 25,
    estado: "revision",
    fechaCreacion: "13 may. 2024",
    dificultad: "normal",
    consignaRaw: "Filipenses 4:13",
    opciones: [],
    sendaColor: getSendaColorClasses("Hijo"),
    grupoEdadId: "grupo-3",
  },
  {
    id: "mock-4",
    titulo: "¿Verdadero o falso?",
    consigna: "Pon a prueba tu conocimiento",
    tipoIcon: "fa-circle-check",
    tipoIconColor: "text-emerald-500",
    tipoBadgeBg: "bg-emerald-100",
    tipoNombre: "Verdadero/Falso",
    tipoCodigo: "verdadero_falso",
    temaId: "tema-4",
    temaNombre: "Daniel en el foso de los leones",
    temaSlug: "daniel-foso",
    temaEstado: "publicado",
    pasoId: null,
    franjaEdad: "Medianos (9-11)",
    xpText: "+15 XP",
    xp: 15,
    estado: "publicada",
    fechaCreacion: "12 may. 2024",
    dificultad: "facil",
    consignaRaw: "Pon a prueba tu conocimiento",
    opciones: [],
    sendaColor: getSendaColorClasses("Padre"),
    grupoEdadId: "grupo-2",
  },
  {
    id: "mock-5",
    titulo: "Sopa de letras",
    consigna: "Encuentra las palabras",
    tipoIcon: "fa-border-all",
    tipoIconColor: "text-violet-600",
    tipoBadgeBg: "bg-violet-100",
    tipoNombre: "Sopa de letras",
    tipoCodigo: "sopa_letras",
    temaId: "tema-5",
    temaNombre: "La oración",
    temaSlug: "la-oracion",
    temaEstado: "publicado",
    pasoId: null,
    franjaEdad: "Grandes (12-14)",
    xpText: "+20 XP",
    xp: 20,
    estado: "publicada",
    fechaCreacion: "11 may. 2024",
    dificultad: "dificil",
    consignaRaw: "Encuentra las palabras",
    opciones: [],
    sendaColor: getSendaColorClasses("Hijo"),
    grupoEdadId: "grupo-3",
  },
  {
    id: "mock-6",
    titulo: "Ordena el versículo",
    consigna: "Pon en el orden correcto",
    tipoIcon: "fa-puzzle-piece",
    tipoIconColor: "text-orange-500",
    tipoBadgeBg: "bg-orange-100",
    tipoNombre: "Ordenar",
    tipoCodigo: "ordenar_verso",
    temaId: "tema-2",
    temaNombre: "El perdón",
    temaSlug: "el-perdon",
    temaEstado: "borrador",
    pasoId: null,
    franjaEdad: "Pequeños (6-8)",
    xpText: "+20 XP",
    xp: 20,
    estado: "borrador",
    fechaCreacion: "10 may. 2024",
    dificultad: "facil",
    consignaRaw: "Pon en el orden correcto",
    opciones: [],
    sendaColor: getSendaColorClasses("Espíritu"),
    grupoEdadId: "grupo-1",
  },
  {
    id: "mock-7",
    titulo: "Memoria: Pasajes clave",
    consigna: "Encuentra los pares",
    tipoIcon: "fa-image",
    tipoIconColor: "text-sky-500",
    tipoBadgeBg: "bg-sky-100",
    tipoNombre: "Memoria",
    tipoCodigo: "memoria",
    temaId: "tema-6",
    temaNombre: "Dios cuida de mí",
    temaSlug: "dios-cuida",
    temaEstado: "publicado",
    pasoId: null,
    franjaEdad: "Pequeños (6-8)",
    xpText: "+15 XP",
    xp: 15,
    estado: "publicada",
    fechaCreacion: "9 may. 2024",
    dificultad: "facil",
    consignaRaw: "Encuentra los pares",
    opciones: [],
    sendaColor: getSendaColorClasses("Padre"),
    grupoEdadId: "grupo-1",
  },
  {
    id: "mock-8",
    titulo: "Desafío express",
    consigna: "Responde rápido",
    tipoIcon: "fa-star",
    tipoIconColor: "text-pink-500",
    tipoBadgeBg: "bg-pink-100",
    tipoNombre: "Quiz",
    tipoCodigo: "quiz",
    temaId: "tema-1",
    temaNombre: "La creación de Dios",
    temaSlug: "la-creacion",
    temaEstado: "revision",
    pasoId: null,
    franjaEdad: "Medianos (9-11)",
    xpText: "+10 XP",
    xp: 10,
    estado: "revision",
    fechaCreacion: "8 may. 2024",
    dificultad: "normal",
    consignaRaw: "Responde rápido",
    opciones: [],
    sendaColor: getSendaColorClasses("Padre"),
    grupoEdadId: "grupo-2",
  },
];
